services:
  - type: web
    name: alma-chan
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /
    envVars:
      - key: WEB_PORT
        value: "3000"
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        value: mongodb+srv://YOUR_USER:YOUR_PASS@cluster0.xxxxx.mongodb.net/alma-chan?retryWrites=true&w=majority
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
