services:
  - type: web
    name: alma-chan
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /
    envVars:
      - key: WEB_PORT
        value: "3000"
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
